<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQIXMx1i\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQIXMx1i/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQIXMx1i.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQIXMx1i\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQIXMx1i\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QIXMx1i',
    'container.build_id' => '506c8eaf',
    'container.build_time' => 1562777675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQIXMx1i');
