# config/routes.yaml

#
# ROUTES OF USER
#
app_user_new:
    path: /user/new
    controller: App\Controller\UserController::new

app_pet_new:
    path: /pet/new
    controller: App\Controller\PetController::new

app_teste_new:
    path: /teste/new
    controller: App\Controller\TesteController::new

# 
# ROUTES OF VETERINARY
#
vet_index:
    path: /veterinary
    controller: App\Controller\VeterinaryController::index

vet_new:
    path: /veterinary/new
    controller: App\Controller\VeterinaryController::new

vet_list: 
    path: /veterinary/list
    controller: App\Controller\VeterinaryController::list

vet_edit:
    path: /veterinary/edit/{id}
    controller: App\Controller\VeterinaryController::edit

vet_remove:
    path: /veterinary/remove/{id}
    controller: App\Controller\VeterinaryController::remove

# 
# ROUTES OF CLINIC
#
clinic_index:
    path: /clinic
    controller: App\Controller\ClinicController::index

clinic_new:
    path: /clinic/new
    controller: App\Controller\ClinicController::new

clinic_list:
    path: /clinic/list
    controller: App\Controller\ClinicController::list

clinic_edit:
    path: /clinic/edit/{id}
    controller: App\Controller\ClinicController::edit

clinic_remove:
    path: /clinic/remove/{id}
    controller: App\Controller\ClinicController::remove

# 
# ROUTES OF PET
#
pet_index:
    path: /pet
    controller: App\Controller\PetController::index

pet_new:
    path: /pet/new

pet_list:
    path: /pet/list
    controller: App\Controller\PetController::list

pet_edit:
    path: /pet/edit/{id}
    controller: App\Controller\PetController::edit

pet_remove:
    path: /pet/remove/{id}
    controller: App\Controller\PetController::remove
