# config/routes.yaml

#
# ROUTES OF HOME
#

home_index:
    path: /
    controller: App\Controller\HomeController::index

app_teste_new:
    path: /teste/new
    controller: App\Controller\TesteController::new

#
# ROUTES OF USER
#
user_index:
    path: /user
    controller: App\Controller\UserController::index

user_new:
    path: /user/new
    controller: App\Controller\UserController::new

user_list: 
    path: /user/list
    controller: App\Controller\UserController::list

user_edit:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit

user_remove:
    path: /user/remove/{id}
    controller: App\Controller\UserController::remove

# 
# ROUTES OF VETERINARY
#
vet_index:
    path: /veterinary
    controller: App\Controller\VeterinaryController::index

vet_new:
    path: /veterinary/new
    controller: App\Controller\VeterinaryController::new

vet_list: 
    path: /veterinary/list
    controller: App\Controller\VeterinaryController::list

vet_edit:
    path: /veterinary/edit/{id}
    controller: App\Controller\VeterinaryController::edit

vet_remove:
    path: /veterinary/remove/{id}
    controller: App\Controller\VeterinaryController::remove

# 
# ROUTES OF CLINIC
#
clinic_index:
    path: /clinic
    controller: App\Controller\ClinicController::index

clinic_new:
    path: /clinic/new
    controller: App\Controller\ClinicController::new

clinic_list:
    path: /clinic/list
    controller: App\Controller\ClinicController::list

clinic_edit:
    path: /clinic/edit/{id}
    controller: App\Controller\ClinicController::edit

clinic_remove:
    path: /clinic/remove/{id}
    controller: App\Controller\ClinicController::remove

# 
# ROUTES OF PET
#
pet_index:
    path: /pet
    controller: App\Controller\PetController::index

pet_new:
    path: /pet/new
    controller: App\Controller\PetController::new

pet_list:
    path: /pet/list
    controller: App\Controller\PetController::list

pet_edit:
    path: /pet/edit/{id}
    controller: App\Controller\PetController::edit

pet_remove:
    path: /pet/remove/{id}
    controller: App\Controller\PetController::remove

#
# API ROUTES
#

api_index:
    path: /api/user
    controller: App\Controller\ApiController::index
    defaults:
        _format: json

api_user_list:
    path: /api/user/list
    controller: App\Controller\ApiController::userList
    defaults:
        _format: json
    methods: GET

api_user_id:
    path: /api/user/{id}
    controller: App\Controller\ApiController::userId
    defaults:
        _format: json
    methods: GET

api_user_new:
    path: /api/user/new
    controller: App\Controller\ApiController::userNew
    defaults:
        _format: json
    methods: POST

api_user_edit:
    path: /api/user/edit/{id}
    controller: App\Controller\ApiController::userEdit
    defaults:
        _format: json
    methods: PUT

api_user_delete:
    path: /api/user/delete/{id}
    controller: App\Controller\ApiController::userDelete
    defaults:
        _format: json
    methods: DELETE