# config/routes.yaml

#
# ROUTES OF HOME
#

home_index:
    path: /
    controller: App\Controller\HomeController::index

app_teste_new:
    path: /teste/new
    controller: App\Controller\TesteController::new

#
# ROUTES OF USER
#
user_index:
    path: /user
    controller: App\Controller\UserController::index

user_new:
    path: /user/new
    controller: App\Controller\UserController::new

user_list: 
    path: /user/list
    controller: App\Controller\UserController::list

user_edit:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit

user_remove:
    path: /user/remove/{id}
    controller: App\Controller\UserController::remove

# 
# ROUTES OF VETERINARY
#
vet_index:
    path: /veterinary
    controller: App\Controller\VeterinaryController::index

vet_new:
    path: /veterinary/new
    controller: App\Controller\VeterinaryController::new

vet_list: 
    path: /veterinary/list
    controller: App\Controller\VeterinaryController::list

vet_edit:
    path: /veterinary/edit/{id}
    controller: App\Controller\VeterinaryController::edit

vet_remove:
    path: /veterinary/remove/{id}
    controller: App\Controller\VeterinaryController::remove

# 
# ROUTES OF CLINIC
#
clinic_index:
    path: /clinic
    controller: App\Controller\ClinicController::index

clinic_new:
    path: /clinic/new
    controller: App\Controller\ClinicController::new

clinic_list:
    path: /clinic/list
    controller: App\Controller\ClinicController::list

clinic_edit:
    path: /clinic/edit/{id}
    controller: App\Controller\ClinicController::edit

clinic_remove:
    path: /clinic/remove/{id}
    controller: App\Controller\ClinicController::remove

# 
# ROUTES OF PET
#
pet_index:
    path: /pet
    controller: App\Controller\PetController::index

pet_new:
    path: /pet/new
    controller: App\Controller\PetController::new

pet_list:
    path: /pet/list
    controller: App\Controller\PetController::list

pet_edit:
    path: /pet/edit/{id}
    controller: App\Controller\PetController::edit

pet_remove:
    path: /pet/remove/{id}
    controller: App\Controller\PetController::remove

#
# API USER ROUTES
#

api_user_index:
    path: /api/user
    controller: App\Controller\ApiUserController::index
    defaults:
        _format: json

api_user_list:
    path: /api/user/list
    controller: App\Controller\ApiUserController::userList
    defaults:
        _format: json
    methods: GET

api_user_show:
    path: /api/user/{id}
    controller: App\Controller\ApiUserController::show
    defaults:
        _format: json
    methods: GET

api_user_new:
    path: /api/user/new
    controller: App\Controller\ApiUserController:new
    defaults:
        _format: json
    methods: POST

api_user_edit:
    path: /api/user/edit/{id}
    controller: App\Controller\ApiUserController::edit
    defaults:
        _format: json
    methods: PUT

api_user_delete:
    path: /api/user/delete/{id}
    controller: App\Controller\ApiUserController::delete
    defaults:
        _format: json
    methods: DELETE

#
# API CLINIC ROUTES
#

api_clinic_index:
    path: /api/clinic
    controller: App\Controller\ApiClinicController::index
    defaults:
        _format: json

api_clinic_list:
    path: /api/clinic/list
    controller: App\Controller\ApiClinicController::list
    defaults:
        _format: json
    methods: GET

api_clinic_show:
    path: /api/clinic/{id}
    controller: App\Controller\ApiClinicController::show
    defaults:
        _format: json
    methods: GET

api_clinic_new:
    path: /api/clinic/new
    controller: App\Controller\ApiClinicController:new
    defaults:
        _format: json
    methods: POST

api_clinic_edit:
    path: /api/clinic/edit/{id}
    controller: App\Controller\ApiClinicController::edit
    defaults:
        _format: json
    methods: PUT

api_clinic_delete:
    path: /api/clinic/delete/{id}
    controller: App\Controller\ApiClinicController::delete
    defaults:
        _format: json
    methods: DELETE

#
# API VETERINARY ROUTES
#

api_veterinary_index:
    path: /api/veterinary
    controller: App\Controller\ApiVeterinaryController::index
    defaults:
        _format: json

api_veterinary_list:
    path: /api/veterinary/list
    controller: App\Controller\ApiVeterinaryController::list
    defaults:
        _format: json
    methods: GET

api_veterinary_show:
    path: /api/veterinary/{id}
    controller: App\Controller\ApiVeterinaryController::show
    defaults:
        _format: json
    methods: GET

api_veterinary_new:
    path: /api/veterinary/new
    controller: App\Controller\ApiVeterinaryController:new
    defaults:
        _format: json
    methods: POST

api_veterinary_edit:
    path: /api/veterinary/edit/{id}
    controller: App\Controller\ApiVeterinaryController::edit
    defaults:
        _format: json
    methods: PUT

api_veterinary_delete:
    path: /api/veterinary/delete/{id}
    controller: App\Controller\ApiVeterinaryController::delete
    defaults:
        _format: json
    methods: DELETE