# config/routes.yaml

#
# ROUTES OF HOME
#

home_index:
    path: /
    controller: App\Controller\HomeController::index

app_teste_new:
    path: /teste/new
    controller: App\Controller\TesteController::new

#
# ROUTES OF USER
#
user_index:
    path: /user
    controller: App\Controller\UserController::index

user_new:
    path: /user/new
    controller: App\Controller\UserController::new

user_list: 
    path: /user/list
    controller: App\Controller\UserController::list

user_edit:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit

user_remove:
    path: /user/remove/{id}
    controller: App\Controller\UserController::remove

# 
# ROUTES OF VETERINARY
#
vet_index:
    path: /veterinary
    controller: App\Controller\VeterinaryController::index

vet_new:
    path: /veterinary/new
    controller: App\Controller\VeterinaryController::new

vet_list: 
    path: /veterinary/list
    controller: App\Controller\VeterinaryController::list

vet_edit:
    path: /veterinary/edit/{id}
    controller: App\Controller\VeterinaryController::edit

vet_remove:
    path: /veterinary/remove/{id}
    controller: App\Controller\VeterinaryController::remove

# 
# ROUTES OF CLINIC
#
clinic_index:
    path: /clinic
    controller: App\Controller\ClinicController::index

clinic_new:
    path: /clinic/new
    controller: App\Controller\ClinicController::new

clinic_list:
    path: /clinic/list
    controller: App\Controller\ClinicController::list

clinic_edit:
    path: /clinic/edit/{id}
    controller: App\Controller\ClinicController::edit

clinic_remove:
    path: /clinic/remove/{id}
    controller: App\Controller\ClinicController::remove

# 
# ROUTES OF PET
#
pet_index:
    path: /pet
    controller: App\Controller\PetController::index

pet_new:
    path: /pet/new
    controller: App\Controller\PetController::new

pet_list:
    path: /pet/list
    controller: App\Controller\PetController::list

pet_edit:
    path: /pet/edit/{id}
    controller: App\Controller\PetController::edit

pet_remove:
    path: /pet/remove/{id}
    controller: App\Controller\PetController::remove

#
# API USER ROUTES
#

api_users_list:
    path: api/v1/users
    controller: App\Controller\Api\UserController::list
    defaults:
        _format: json
    methods: GET

api_users_show:
    path: api/v1/users/{id}
    controller: App\Controller\Api\UserController::show
    defaults:
        _format: json
    methods: GET

api_users_new:
    path: api/v1/users
    controller: App\Controller\Api\UserController:new
    defaults:
        _format: json
    methods: POST

api_users_edit:
    path: api/v1/users/{id}
    controller: App\Controller\Api\UserController::edit
    defaults:
        _format: json
    methods: PUT

api_users_delete:
    path: api/v1/users/{id}
    controller: App\Controller\Api\UserController::delete
    defaults:
        _format: json
    methods: DELETE

#
# API CLINIC ROUTES
#

api_clinics_list:
    path: api/v1/clinics
    controller: App\Controller\Api\ClinicController::list
    defaults:
        _format: json
    methods: GET

api_clinics_show:
    path: api/v1/clinics/{id}
    controller: App\Controller\Api\ClinicController::show
    defaults:
        _format: json
    methods: GET

api_clinics_show_veterinaries:
    path: api/v1/clinics/{id}/addresses
    controller: App\Controller\Api\ClinicController::showAddress
    defaults:
        _format: json
    methods: GET

api_clinics_new:
    path: api/v1/clinics
    controller: App\Controller\Api\ClinicController:new
    defaults:
        _format: json
    methods: POST

api_clinics_edit:
    path: api/v1/clinics/{id}
    controller: App\Controller\Api\ClinicController::edit
    defaults:
        _format: json
    methods: PUT

api_clinics_delete:
    path: api/v1/clinics/{id}
    controller: App\Controller\Api\ClinicController::delete
    defaults:
        _format: json
    methods: DELETE

#
# API VETERINARY ROUTES
#

api_veterinaries_list:
    path: api/v1/veterinaries
    controller: App\Controller\Api\VeterinaryController::list
    defaults:
        _format: json
    methods: GET

api_veterinaries_show:
    path: api/v1/veterinaries/{id}
    controller: App\Controller\Api\VeterinaryController::show
    defaults:
        _format: json
    methods: GET

api_veterinaries_show_address:
    path: api/v1/veterinaries/{id}/addresses
    controller: App\Controller\Api\VeterinaryController::showAddress
    defaults:
        _format: json
    methods: GET

api_veterinaries_new:
    path: api/v1/veterinaries
    controller: App\Controller\Api\VeterinaryController:new
    defaults:
        _format: json
    methods: POST

api_veterinaries_edit:
    path: api/v1/veterinaries/{id}
    controller: App\Controller\Api\VeterinaryController::edit
    defaults:
        _format: json
    methods: PUT

api_veterinaries_delete:
    path: api/v1/veterinaries/{id}
    controller: App\Controller\Api\VeterinaryController::delete
    defaults:
        _format: json
    methods: DELETE

#
# API PET ROUTES
#

api_pets_list:
    path: api/v1/pets
    controller: App\Controller\Api\PetController::list
    defaults:
        _format: json
    methods: GET

api_pets_show:
    path: api/v1/pets/{id}
    controller: App\Controller\Api\PetController::show
    defaults:
        _format: json
    methods: GET

api_pets_show_owner:
    path: api/v1/pets/{id}/owners
    controller: App\Controller\Api\PetController::showOwner
    defaults:
        _format: json
    methods: GET

api_pets_show_owner_address:
    path: api/v1/pets/{id}/owners/addresses
    controller: App\Controller\Api\PetController::showOwnerAddress
    defaults:
        _format: json
    methods: GET

api_pets_new:
    path: api/v1/pets
    controller: App\Controller\Api\PetController:new
    defaults:
        _format: json
    methods: POST

api_pets_edit:
    path: api/v1/pets/{id}
    controller: App\Controller\Api\PetController::edit
    defaults:
        _format: json
    methods: PUT

api_pets_delete:
    path: api/v1/pets/{id}
    controller: App\Controller\Api\PetController::delete
    defaults:
        _format: json
    methods: DELETE