# config/validator/validation.yaml
App\Entity\User:
    properties:
        userName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
