<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sY1iup4' shared service.

return $this->privates['.service_locator.sY1iup4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'id' => ['privates', '.errored..service_locator.sY1iup4.App\\Entity\\Pet', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Pet" but no such service exists.'],
], [
    'id' => 'App\\Entity\\Pet',
]);
