<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.t6kg4AP' shared service.

return $this->privates['.service_locator.t6kg4AP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'veterinary' => ['privates', '.errored..service_locator.t6kg4AP.App\\Entity\\Veterinary', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Veterinary" but no such service exists.'],
], [
    'veterinary' => 'App\\Entity\\Veterinary',
]);
